### ISSUE TITLE
KotlinEditor class not found

### ISSUE THREAD

**Issue by jrenner** [JetBrains/kotlin-eclipse#45]
```
Plug-in org.jetbrains.kotlin.ui was unable to load class org.jetbrains.kotlin.ui.editors.KotlinEditor.
```

Followed the instructions in the README, and when trying to open a .kt file I get the above error.

Is there a certain way I need to configure eclipse to build/load the kotlin plugin pieces? Other than as specified in the README.md?  Do I somehow have to build the plugins into a jar and include it with my project?

**Comment by goodwinnk** [comment]
I think it's now outdated.
