### ISSUE TITLE
Method allKotlinClasses() is undefined for the type JavaToKotlinClassMap

### ISSUE THREAD

**Issue by tomcashman** [JetBrains/kotlin-eclipse#62]
I received the following error when attempting to build the latest code. Built with Maven 3.0.5 and Java 7.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.18.0:compile (default-compile) on project org.jetbrains.kotlin.core: Compilation failure: Compilation failure:
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/injectors/EclipseInjectorForTopDownAnalyzerForJvm.java:[55,0]
[ERROR] import org.jetbrains.kotlin.types.expressions.LocalClassifierAnalyzer;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The type org.jetbrains.kotlin.types.expressions.LocalClassifierAnalyzer is not visible
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/injectors/EclipseInjectorForTopDownAnalyzerForJvm.java:[133,0]
[ERROR] private final LocalClassifierAnalyzer localClassifierAnalyzer;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] LocalClassifierAnalyzer cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/injectors/EclipseInjectorForTopDownAnalyzerForJvm.java:[218,0]
[ERROR] this.localClassifierAnalyzer = new LocalClassifierAnalyzer();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] LocalClassifierAnalyzer cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/injectors/EclipseInjectorForTopDownAnalyzerForJvm.java:[218,0]
[ERROR] this.localClassifierAnalyzer = new LocalClassifierAnalyzer();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] LocalClassifierAnalyzer cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/injectors/EclipseInjectorForTopDownAnalyzerForJvm.java:[317,0]
[ERROR] expressionTypingComponents.setLocalClassifierAnalyzer(localClassifierAnalyzer);
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] LocalClassifierAnalyzer cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/launch/KotlinCLICompiler.java:[25,0]
[ERROR] import org.jetbrains.kotlin.cli.jvm.compiler.CompilerJarLocator;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.jetbrains.kotlin.cli.jvm.compiler.CompilerJarLocator cannot be resolved
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/launch/KotlinCLICompiler.java:[44,0]
[ERROR] builder.register(CompilerJarLocator.class, new CompilerJarLocator() {
[ERROR] ^^^^^^^^
[ERROR] The method register(Class<T>, T) in the type Services.Builder is not applicable for the arguments (Class<CompilerJarLocator>, new CompilerJarLocator(){})
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/launch/KotlinCLICompiler.java:[44,0]
[ERROR] builder.register(CompilerJarLocator.class, new CompilerJarLocator() {
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] CompilerJarLocator cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/launch/KotlinCLICompiler.java:[44,0]
[ERROR] builder.register(CompilerJarLocator.class, new CompilerJarLocator() {
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] CompilerJarLocator cannot be resolved to a type
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/launch/KotlinCLICompiler.java:[47,0]
[ERROR] public File getCompilerJar() {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] The method getCompilerJar() of type new CompilerJarLocator(){} must override or implement a supertype method
[ERROR] /home/thomas/Tools/kotlin-eclipse/kotlin-eclipse-core/src/org/jetbrains/kotlin/core/resolve/EclipseAnalyzerFacadeForJVM.java:[64,0]
[ERROR] for (ClassDescriptor descriptor : JavaToKotlinClassMap.INSTANCE.allKotlinClasses()) {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] The method allKotlinClasses() is undefined for the type JavaToKotlinClassMap

**Comment by gjroelofs** [comment]
Same issue here; the missing imports are:

- org.jetbrains.kotlin.resolve.PartialBodyResolveProvider
- org.jetbrains.kotlin.resolve.ImportsResolver
- org.jetbrains.kotlin.resolve.TopDownAnalyzer
- org.jetbrains.kotlin.resolve.TypeHierarchyResolver

**Comment by goodwinnk** [comment]
If this issue is still reproducible for you please reopen it at our tracker with the link https://youtrack.jetbrains.com/newIssue?project=KT&clearDraft=true&c=Subsystems+Eclipse+Plugin. We want to store everything in one place and are going to close issue tracker on github.
